import { ActivityIndicator, View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { Image as ExpoImage } from 'expo-image';
import { useEffect, useState } from 'react';
import { Link, useLocalSearchParams, useRouter } from 'expo-router';
import Head from 'expo-router/head';
import { House, Target, Ticket, UsersRound } from 'lucide-react-native';
import { supabase } from '@/lib/supabase';
import { useAppTheme } from '@/hooks/use-theme';
import { useLanguage, type TranslationKey } from '@/lib/i18n';
import { getProductCategory } from '@/lib/product-categories';
import type { Product } from '@/types/database';
import productSeoManifest from '@/generated/product-seo-manifest.json';

const BASE_URL = 'https://jeetobaz.pk';
const DEFAULT_OG_IMAGE = `${BASE_URL}/og-image.png`;
const DEFAULT_TWITTER_IMAGE = `${BASE_URL}/twitter-image.png`;
const PRODUCT_COLUMNS = 'id, name, price, status, current_entries, max_entries, entry_fee, image_url, description, draw_date, live_link, seo_title, meta_description, meta_keywords, slug, indexable';

// Only fields that already exist on `products` (verified live schema, Phase 3.5 audit) are used
// here — no featured/display_order column exists, so there is no secondary ordering signal beyond
// category + entry_fee. `getProductCategory` is the existing, already-in-production classifier
// used by the Home category filters (src/lib/product-categories.ts) — this reuses it as-is rather
// than adding a second classifier or parsing slugs. Fetches the full active set (well under
// Supabase's default row cap for this table's current size) rather than a small `limit`, because
// truncating the candidate pool before sorting by entry_fee proximity could silently drop the
// actual closest match.
const RELATED_PRODUCT_COLUMNS = 'id, name, price, status, current_entries, max_entries, entry_fee, image_url, slug';
const RELATED_PRODUCTS_QUERY_LIMIT = 300;
const RELATED_PRODUCTS_MAX = 4;

type StaticProductEntry = {
  slug: string;
  name: string;
  seoTitle: string;
  metaDescription: string;
  metaKeywords: string;
  indexable: boolean;
  imageUrl: string;
  description: string;
  entryFee: number;
};

// Escapes `<` so a value containing e.g. `</script>` can't break out of the JSON-LD script tag,
// matching the standard safe pattern for embedding JSON inside <script> via dangerouslySetInnerHTML.
function jsonLdHtml(data: object): string {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

// `productSeoManifest` is generated by scripts/generate-product-seo-manifest.mjs, which must run
// before `expo export` (wired into netlify.toml's build command). It is a plain JSON import, so
// it is part of the module graph and synchronously available in every context that loads this
// route module: the Node build-time static render, client web hydration, and the native bundle.
// This avoids relying on any in-memory state being shared between build steps.
const manifestEntries = productSeoManifest as StaticProductEntry[];
const staticProductBySlug = new Map(manifestEntries.map((entry) => [entry.slug, entry]));

// Runs in Node at build time (stable Expo Router API — not the alpha data-loaders feature).
// Pre-generates one static HTML file per known product slug so title/description/canonical/
// robots/OG/Twitter metadata are present in the raw HTML response, not only after client JS
// fetches the product. This is required for crawlers and for WhatsApp/Facebook/Twitter link
// previews, none of which execute JavaScript.
export async function generateStaticParams(): Promise<Array<{ slug: string }>> {
  return manifestEntries.map((entry) => ({ slug: entry.slug }));
}

function firstParam(value: string | string[] | undefined): string {
  if (Array.isArray(value)) return value[0] || '';
  return value || '';
}

export default function ProductDetailScreen() {
  const { theme } = useAppTheme();
  const { t } = useLanguage();
  const router = useRouter();
  const params = useLocalSearchParams<{ slug?: string | string[] }>();
  const slug = firstParam(params.slug);

  const [product, setProduct] = useState<Product | null>(null);
  const [loading, setLoading] = useState(true);
  const [fetchFailed, setFetchFailed] = useState(false);
  const [relatedProducts, setRelatedProducts] = useState<Product[]>([]);

  useEffect(() => {
    let active = true;

    async function loadProduct() {
      if (!slug) {
        if (active) {
          setFetchFailed(true);
          setLoading(false);
        }
        return;
      }

      const { data, error } = await supabase
        .from('products')
        .select(PRODUCT_COLUMNS)
        .eq('slug', slug)
        .maybeSingle();

      if (!active) return;

      if (error || !data) {
        setFetchFailed(true);
      } else {
        setProduct(data as Product);
      }
      setLoading(false);
    }

    loadProduct();
    return () => { active = false; };
  }, [slug]);

  // Independent of the main product fetch above so related products don't wait on it — the
  // current product's entry fee (needed for proximity sorting) is already available synchronously
  // from the static manifest, even before the live product row resolves.
  useEffect(() => {
    let active = true;

    async function loadRelatedProducts() {
      if (!slug) return;
      const staticEntry = staticProductBySlug.get(slug);
      const currentEntryFee = staticEntry?.entryFee ?? 1;
      const currentCategory = staticEntry?.name ? getProductCategory(staticEntry.name) : null;

      const { data, error } = await supabase
        .from('products')
        .select(RELATED_PRODUCT_COLUMNS)
        .eq('status', 'active')
        .neq('slug', slug)
        .not('slug', 'is', null)
        .limit(RELATED_PRODUCTS_QUERY_LIMIT);

      if (!active) return;
      if (error || !data) {
        setRelatedProducts([]);
        return;
      }

      // "Open" = active status (already filtered above) and spots still remaining — a full
      // product isn't accepting entries anymore, so it isn't a useful recommendation.
      const openCandidates = (data as Product[]).filter(
        (candidate) => (candidate.current_entries || 0) < candidate.max_entries
      );

      // Stable id tie-break so the result is deterministic for a given underlying data set.
      function byEntryFeeProximity(a: Product, b: Product) {
        const feeDiffA = Math.abs((a.entry_fee || 1) - currentEntryFee);
        const feeDiffB = Math.abs((b.entry_fee || 1) - currentEntryFee);
        if (feeDiffA !== feeDiffB) return feeDiffA - feeDiffB;
        return a.id.localeCompare(b.id);
      }

      let picked: Product[];
      if (currentCategory) {
        // Category-first: prefer candidates the existing classifier resolves to the same
        // category as the current product, ranked by closest entry_fee. If that doesn't fill
        // all 4 slots, top up with the next-closest entry_fee matches from any other category.
        const sameCategory = openCandidates
          .filter((candidate) => getProductCategory(candidate.name) === currentCategory)
          .sort(byEntryFeeProximity);
        picked = sameCategory.slice(0, RELATED_PRODUCTS_MAX);

        if (picked.length < RELATED_PRODUCTS_MAX) {
          const pickedIds = new Set(picked.map((item) => item.id));
          const otherCandidates = openCandidates
            .filter((candidate) => !pickedIds.has(candidate.id))
            .sort(byEntryFeeProximity);
          picked = picked.concat(otherCandidates.slice(0, RELATED_PRODUCTS_MAX - picked.length));
        }
      } else {
        // The current product doesn't resolve to any known category — skip category matching
        // entirely and fall back directly to closest entry_fee across all open candidates.
        picked = [...openCandidates].sort(byEntryFeeProximity).slice(0, RELATED_PRODUCTS_MAX);
      }

      setRelatedProducts(picked);
    }

    loadRelatedProducts();
    return () => { active = false; };
  }, [slug]);

  // The generated manifest (imported above, see productSeoManifest) is available synchronously
  // on the very first render, including during the Node build-time static render pass. The live
  // Supabase fetch above only resolves client-side after hydration. Preferring live data once it
  // arrives (it is fresher) but falling back to the manifest entry means the exported HTML always
  // has correct metadata, even before/without the client fetch completing.
  const staticEntry = slug ? staticProductBySlug.get(slug) : undefined;
  const metaSource = product
    ? {
        name: product.name,
        seoTitle: product.seo_title || '',
        metaDescription: product.meta_description || '',
        metaKeywords: product.meta_keywords || '',
        indexable: product.indexable !== false,
        imageUrl: product.image_url || '',
        description: product.description || '',
        entryFee: product.entry_fee || 1,
      }
    : staticEntry
      ? {
          name: staticEntry.name,
          seoTitle: staticEntry.seoTitle,
          metaDescription: staticEntry.metaDescription,
          metaKeywords: staticEntry.metaKeywords,
          indexable: staticEntry.indexable,
          imageUrl: staticEntry.imageUrl,
          description: staticEntry.description,
          entryFee: staticEntry.entryFee,
        }
      : null;

  if (!metaSource && loading) {
    return (
      <>
      <Head>
        <meta name="robots" content="noindex, follow" />
      </Head>
      <View style={[styles.centerContainer, { backgroundColor: theme.background }]}>
        <ActivityIndicator color={theme.gold} size="large" />
      </View>
      </>
    );
  }

  if (!metaSource && (fetchFailed || !slug)) {
    return (
      <>
      <Head>
        <title>Prize Not Found | JeetoBaz</title>
        <meta name="robots" content="noindex, follow" />
        <meta name="description" content="The JeetoBaz prize campaign you requested could not be found. Explore other active draws." />
      </Head>
      <View style={[styles.centerContainer, { backgroundColor: theme.background }]}>
        <Text style={[styles.notFoundCode, { color: theme.gold }]}>404</Text>
        <Text style={[styles.notFoundTitle, { color: theme.text }]}>Prize Not Found</Text>
        <Text style={[styles.notFoundMessage, { color: theme.muted }]}>
          This prize campaign does not exist, is no longer available, or the link is incorrect.
        </Text>
        <TouchableOpacity
          style={[styles.notFoundButton, { backgroundColor: theme.gold }]}
          onPress={() => router.replace('/')}
        >
          <House color="#000" size={20} />
          <Text style={styles.notFoundButtonText}>Back to Home</Text>
        </TouchableOpacity>
      </View>
      </>
    );
  }

  // metaSource is guaranteed non-null past this point (static fallback or live product).
  const meta = metaSource!;
  const pageUrl = `${BASE_URL}/product/${slug}`;
  const pageTitle = meta.seoTitle.trim() || `Win ${meta.name} in Pakistan | JeetoBaz`;
  const pageDescription = meta.metaDescription.trim()
    || meta.description.trim()
    || `Join JeetoBaz for a chance to win ${meta.name} through our transparent prize campaign.`;
  const robotsContent = meta.indexable ? 'index, follow' : 'noindex, follow';
  const ogImage = meta.imageUrl || DEFAULT_OG_IMAGE;
  const twitterImage = meta.imageUrl || DEFAULT_TWITTER_IMAGE;

  const currentEntries = product?.current_entries || 0;
  const maxEntries = product?.max_entries || 1;
  const spotsLeft = Math.max(maxEntries - currentEntries, 0);
  const entryFee = meta.entryFee;

  // `product` (live entry counts) is only available client-side after hydration; the build-time
  // static render only has `meta.entryFee` from the manifest. Availability defaults to InStock
  // when live counts aren't known yet, since that is the common case and this markup is refreshed
  // on every deploy rather than needing to be real-time accurate.
  const availability = product ? (spotsLeft > 0 ? 'https://schema.org/InStock' : 'https://schema.org/SoldOut') : 'https://schema.org/InStock';

  const productJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: meta.name,
    description: pageDescription,
    image: ogImage,
    offers: {
      '@type': 'Offer',
      url: pageUrl,
      priceCurrency: 'PKR',
      price: String(entryFee),
      availability,
    },
  };

  const breadcrumbJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${BASE_URL}/` },
      { '@type': 'ListItem', position: 2, name: 'Explore', item: `${BASE_URL}/explore` },
      { '@type': 'ListItem', position: 3, name: meta.name, item: pageUrl },
    ],
  };

  function handleEnter() {
    if (!product) return;
    router.push({
      pathname: '/payment',
      params: {
        productId: product.id,
        productName: product.name,
        entryFee,
      },
    });
  }

  return (
    <>
    <Head>
      <title>{pageTitle}</title>
      <meta name="robots" content={robotsContent} />
      <meta name="description" content={pageDescription} />
      {meta.metaKeywords ? <meta name="keywords" content={meta.metaKeywords} /> : null}
      <link rel="canonical" href={pageUrl} />
      <meta property="og:type" content="product" />
      <meta property="og:title" content={pageTitle} />
      <meta property="og:description" content={pageDescription} />
      <meta property="og:url" content={pageUrl} />
      <meta property="og:site_name" content="JeetoBaz" />
      <meta property="og:image" content={ogImage} />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@jeetobaz" />
      <meta name="twitter:title" content={pageTitle} />
      <meta name="twitter:description" content={pageDescription} />
      <meta name="twitter:image" content={twitterImage} />
      <script type="application/ld+json">{jsonLdHtml(productJsonLd)}</script>
      <script type="application/ld+json">{jsonLdHtml(breadcrumbJsonLd)}</script>
    </Head>
    <ScrollView style={[styles.container, { backgroundColor: theme.background }]}>
      <View style={[styles.header, { backgroundColor: theme.surface, borderBottomColor: theme.gold }]}>
        <TouchableOpacity onPress={() => router.back()}>
          <Text style={[styles.backBtn, { color: theme.primary }]}>← {t('back')}</Text>
        </TouchableOpacity>
      </View>

      <View style={{ height: 260 }}>
        {meta.imageUrl ? (
          <ExpoImage
            source={{ uri: meta.imageUrl }}
            accessibilityLabel={`${meta.name} prize`}
            contentFit="contain"
            cachePolicy="disk"
            style={styles.productImage}
          />
        ) : (
          <View style={[styles.productImageFallback, { backgroundColor: theme.surfaceAlt }]}>
            <Ticket color={theme.gold} size={38} />
          </View>
        )}
      </View>

      <View style={[styles.body, { backgroundColor: theme.surface, borderColor: theme.border }]}>
        <Text role="heading" aria-level={1} style={[styles.productName, { color: theme.text }]}>
          {meta.name}
        </Text>

        {meta.description ? (
          <Text style={[styles.description, { color: theme.muted }]}>{meta.description}</Text>
        ) : null}

        {product ? (
          <>
            <View style={styles.priceRow}>
              <Text style={[styles.originalPrice, { color: theme.gold }]}>Rs. {product.price?.toLocaleString()}</Text>
              <View style={[styles.entryBadge, { backgroundColor: theme.goldSoft }]}>
                <Text style={[styles.entryFee, { color: theme.gold }]}>{t('entryFee')}: Rs. {entryFee}</Text>
              </View>
            </View>

            <View style={styles.iconRow}>
              <UsersRound color={theme.muted} size={16} />
              <Text style={[styles.participants, { color: theme.muted }]}>
                {currentEntries.toLocaleString()} {t('participants')} • {spotsLeft.toLocaleString()} {t('spotsLeft')}
              </Text>
            </View>

            <TouchableOpacity
              style={[styles.enterButton, { backgroundColor: theme.gold }]}
              onPress={handleEnter}
              accessibilityRole="button"
              accessibilityLabel={`${t('enterFor')} Rs.${entryFee}: ${meta.name}`}
            >
              <Target color="#000" size={19} />
              <Text style={styles.enterButtonText}>{t('enterFor')} Rs.{entryFee}</Text>
            </TouchableOpacity>
          </>
        ) : (
          <ActivityIndicator color={theme.gold} style={{ marginTop: 8 }} />
        )}
      </View>

      {relatedProducts.length > 0 ? (
        <View style={styles.relatedSection}>
          <Text style={[styles.relatedTitle, { color: theme.text }]}>{t('relatedProducts')}</Text>
          <View style={styles.relatedGrid}>
            {relatedProducts.map((related) => (
              <RelatedProductCard key={related.id} product={related} theme={theme} t={t} />
            ))}
          </View>
        </View>
      ) : null}
    </ScrollView>
    </>
  );
}

function RelatedProductCard({
  product,
  theme,
  t,
}: {
  product: Product;
  theme: ReturnType<typeof useAppTheme>['theme'];
  t: (key: TranslationKey) => string;
}) {
  const spotsLeft = Math.max(product.max_entries - (product.current_entries || 0), 0);

  if (!product.slug) return null;

  return (
    <Link href={`/product/${product.slug}`} asChild>
      <TouchableOpacity
        style={StyleSheet.flatten([styles.relatedCard, { backgroundColor: theme.surface, borderColor: theme.border }])}
        accessibilityRole="link"
        accessibilityLabel={`${product.name}: ${t('entryFee')} Rs.${product.entry_fee || 1}`}
      >
        {product.image_url ? (
          <ExpoImage
            source={{ uri: product.image_url }}
            accessibilityLabel={`${product.name} prize`}
            contentFit="contain"
            cachePolicy="disk"
            style={styles.relatedImage}
          />
        ) : (
          <View style={[styles.relatedImageFallback, { backgroundColor: theme.surfaceAlt }]}>
            <Ticket color={theme.gold} size={26} />
          </View>
        )}
        <Text numberOfLines={2} style={[styles.relatedName, { color: theme.text }]}>{product.name}</Text>
        <View style={[styles.relatedEntryBadge, { backgroundColor: theme.goldSoft }]}>
          <Text style={[styles.relatedEntryFee, { color: theme.gold }]}>{t('entryFee')}: Rs. {product.entry_fee || 1}</Text>
        </View>
        <Text numberOfLines={1} style={[styles.relatedSpots, { color: theme.muted }]}>{spotsLeft.toLocaleString()} {t('spotsLeft')}</Text>
      </TouchableOpacity>
    </Link>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  centerContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },

  notFoundCode: { fontSize: 80, fontWeight: '800', marginBottom: 8 },
  notFoundTitle: { fontSize: 26, fontWeight: '700', marginBottom: 12 },
  notFoundMessage: { fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 32, maxWidth: 400 },
  notFoundButton: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 14, paddingHorizontal: 28, borderRadius: 12 },
  notFoundButtonText: { color: '#000', fontSize: 16, fontWeight: '700' },

  header: { padding: 20, borderBottomWidth: 2 },
  backBtn: { fontSize: 16, fontWeight: 'bold' },

  productImage: { width: '100%', height: 260 },
  productImageFallback: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  body: { margin: 15, borderRadius: 16, borderWidth: 1, padding: 20 },

  relatedSection: { paddingHorizontal: 15, marginTop: 5, marginBottom: 30 },
  relatedTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12 },
  relatedGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  relatedCard: { width: '47%', borderRadius: 12, borderWidth: 1, padding: 10 },
  relatedImage: { width: '100%', height: 90, marginBottom: 8 },
  relatedImageFallback: { width: '100%', height: 90, marginBottom: 8, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
  relatedName: { fontSize: 13, fontWeight: '700', marginBottom: 8, minHeight: 34 },
  relatedEntryBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginBottom: 6 },
  relatedEntryFee: { fontSize: 11, fontWeight: '700' },
  relatedSpots: { fontSize: 11 },
  productName: { fontSize: 22, fontWeight: 'bold', marginBottom: 10 },
  description: { fontSize: 14, lineHeight: 20, marginBottom: 16 },

  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  originalPrice: { fontSize: 18, fontWeight: 'bold', textDecorationLine: 'line-through' },
  entryBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  entryFee: { fontSize: 13, fontWeight: '700' },

  iconRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 20 },
  participants: { fontSize: 13 },

  enterButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 16, borderRadius: 12 },
  enterButtonText: { fontSize: 16, fontWeight: 'bold', color: '#000' },
});
