import { ActivityIndicator, View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { Image as ExpoImage } from 'expo-image';
import { useEffect, useState } from 'react';
import { Link, useLocalSearchParams, useRouter } from 'expo-router';
import Head from 'expo-router/head';
import { House, Target, Ticket, UsersRound } from 'lucide-react-native';
import { supabase } from '@/lib/supabase';
import { useAppTheme } from '@/hooks/use-theme';
import { useLanguage, type TranslationKey } from '@/lib/i18n';
import { ButtonSheen } from '@/components/motion';
import { ProductHeroImage } from '@/components/product-hero-image';
import { getProductCategory } from '@/lib/product-categories';
import { recordRecentlyViewedProduct } from '@/lib/recently-viewed';
import { pageSchema } from '@/lib/structured-data';
import type { Product } from '@/types/database';
import productSeoManifest from '@/generated/product-seo-manifest.json';
import { useSafeBack } from '@/lib/safe-back';

const BASE_URL = 'https://jeetobaz.pk';
const DEFAULT_OG_IMAGE = `${BASE_URL}/og-image.png`;
const DEFAULT_TWITTER_IMAGE = `${BASE_URL}/twitter-image.png`;
const IPHONE_18_PRO_MAX_SLUG = 'win-iphone-18-pro-max-jeetobaz-pk';
const PRODUCT_COLUMNS = 'id, name, price, status, current_entries, max_entries, entry_fee, image_url, description, draw_date, live_link, seo_title, meta_description, meta_keywords, slug, indexable';

// Only fields that already exist on `products` (verified live schema, Phase 3.5 audit) are used
// here — no featured/display_order column exists, so there is no secondary ordering signal beyond
// category + entry_fee. `getProductCategory` is the existing, already-in-production classifier
// used by the Home category filters (src/lib/product-categories.ts) — this reuses it as-is rather
// than adding a second classifier or parsing slugs. Fetches the full active set (well under
// Supabase's default row cap for this table's current size) rather than a small `limit`, because
// truncating the candidate pool before sorting by entry_fee proximity could silently drop the
// actual closest match.
const RELATED_PRODUCT_COLUMNS = 'id, name, price, status, current_entries, max_entries, entry_fee, image_url, slug, category';
const RELATED_PRODUCTS_QUERY_LIMIT = 300;
const RELATED_PRODUCTS_MAX = 4;

type StaticProductEntry = {
  slug: string;
  name: string;
  seoTitle: string;
  metaDescription: string;
  metaKeywords: string;
  indexable: boolean;
  imageUrl: string;
  description: string;
  entryFee: number;
  price: number;
  maxEntries: number;
};

// Escapes `<` so a value containing e.g. `</script>` can't break out of the JSON-LD script tag,
// matching the standard safe pattern for embedding JSON inside <script> via dangerouslySetInnerHTML.
function jsonLdHtml(data: object): string {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

// `productSeoManifest` is generated by scripts/generate-product-seo-manifest.mjs, which must run
// before `expo export` (wired into package.json's build script, used by the GitHub Pages
// workflow). It is a plain JSON import, so
// it is part of the module graph and synchronously available in every context that loads this
// route module: the Node build-time static render, client web hydration, and the native bundle.
// This avoids relying on any in-memory state being shared between build steps.
const manifestEntries = productSeoManifest as StaticProductEntry[];
const staticProductBySlug = new Map(manifestEntries.map((entry) => [entry.slug, entry]));

// Runs in Node at build time (stable Expo Router API — not the alpha data-loaders feature).
// Pre-generates one static HTML file per known product slug so title/description/canonical/
// robots/OG/Twitter metadata are present in the raw HTML response, not only after client JS
// fetches the product. This is required for crawlers and for WhatsApp/Facebook/Twitter link
// previews, none of which execute JavaScript.
export async function generateStaticParams(): Promise<Array<{ slug: string }>> {
  return manifestEntries.map((entry) => ({ slug: entry.slug }));
}

function firstParam(value: string | string[] | undefined): string {
  if (Array.isArray(value)) return value[0] || '';
  return value || '';
}

// Expo Router auto-detects a named `ErrorBoundary` export from a route file and wraps that
// route's component with it (src/lib: node_modules/expo-router/build/useScreens.js `fromImport`).
// Scoped to this route only — if this component throws during render (e.g. Incident 001, a bad
// style prop crashing web hydration), this replaces the blank/unmounted page with a recoverable
// fallback instead of a permanent white screen. Never render `error.message`/stack to the user —
// it may contain internal details — only log it, and only outside production.
export function ErrorBoundary({ error, retry }: { error: Error; retry: () => Promise<void> }) {
  const { theme } = useAppTheme();
  const router = useRouter();

  if (process.env.NODE_ENV === 'development') {
    console.error('[product/[slug]] ErrorBoundary caught an error:', error);
  }

  return (
    <>
    <Head>
      <meta name="robots" content="noindex, follow" />
    </Head>
    <View style={[styles.centerContainer, { backgroundColor: theme.background }]}>
      <Text style={[styles.notFoundTitle, { color: theme.text }]}>Something went wrong</Text>
      <Text style={[styles.notFoundMessage, { color: theme.muted }]}>
        This prize page couldn&apos;t be loaded right now. Please try again.
      </Text>
      <TouchableOpacity
        style={[styles.notFoundButton, { backgroundColor: theme.gold }]}
        onPress={retry}
        accessibilityRole="button"
        accessibilityLabel="Try again"
      >
        <Text style={styles.notFoundButtonText}>Try Again</Text>
      </TouchableOpacity>
      <TouchableOpacity
        style={[styles.notFoundButton, styles.notFoundButtonSecondary, { borderColor: theme.border }]}
        onPress={() => router.replace('/')}
        accessibilityRole="button"
        accessibilityLabel="Back to Home"
      >
        <House color={theme.text} size={20} />
        <Text style={[styles.notFoundButtonText, { color: theme.text }]}>Back to Home</Text>
      </TouchableOpacity>
    </View>
    </>
  );
}

export default function ProductDetailScreen() {
  const { theme } = useAppTheme();
  const { t } = useLanguage();
  const router = useRouter();
  const goBack = useSafeBack();
  const params = useLocalSearchParams<{ slug?: string | string[] }>();
  const slug = firstParam(params.slug);

  const [product, setProduct] = useState<Product | null>(null);
  const [loading, setLoading] = useState(true);
  const [fetchFailed, setFetchFailed] = useState(false);
  const [relatedProducts, setRelatedProducts] = useState<Product[]>([]);

  useEffect(() => {
    let active = true;

    async function loadProduct() {
      if (!slug) {
        if (active) {
          setFetchFailed(true);
          setLoading(false);
        }
        return;
      }

      const { data, error } = await supabase
        .from('products')
        .select(PRODUCT_COLUMNS)
        .eq('slug', slug)
        .maybeSingle();

      if (!active) return;

      if (error || !data) {
        setFetchFailed(true);
      } else {
        setProduct(data as Product);
      }
      setLoading(false);
    }

    loadProduct();
    return () => { active = false; };
  }, [slug]);

  useEffect(() => {
    if (product?.id) void recordRecentlyViewedProduct(product.id);
  }, [product?.id]);

  // Independent of the main product fetch above so related products don't wait on it — the
  // current product's entry fee (needed for proximity sorting) is already available synchronously
  // from the static manifest, even before the live product row resolves.
  useEffect(() => {
    let active = true;

    async function loadRelatedProducts() {
      if (!slug) return;
      const staticEntry = staticProductBySlug.get(slug);
      const currentEntryFee = staticEntry?.entryFee ?? 1;
      const currentCategory = staticEntry?.name ? getProductCategory(staticEntry.name) : null;

      const { data, error } = await supabase
        .from('products')
        .select(RELATED_PRODUCT_COLUMNS)
        .eq('status', 'active')
        .neq('slug', slug)
        .not('slug', 'is', null)
        .limit(RELATED_PRODUCTS_QUERY_LIMIT);

      if (!active) return;
      if (error || !data) {
        setRelatedProducts([]);
        return;
      }

      // "Open" = active status (already filtered above) and spots still remaining — a full
      // product isn't accepting entries anymore, so it isn't a useful recommendation.
      const openCandidates = (data as Product[]).filter(
        (candidate) => (candidate.current_entries || 0) < candidate.max_entries
      );

      // Stable id tie-break so the result is deterministic for a given underlying data set.
      function byEntryFeeProximity(a: Product, b: Product) {
        const feeDiffA = Math.abs((a.entry_fee || 1) - currentEntryFee);
        const feeDiffB = Math.abs((b.entry_fee || 1) - currentEntryFee);
        if (feeDiffA !== feeDiffB) return feeDiffA - feeDiffB;
        return a.id.localeCompare(b.id);
      }

      let picked: Product[];
      if (currentCategory) {
        // Category-first: prefer candidates the existing classifier resolves to the same
        // category as the current product, ranked by closest entry_fee. If that doesn't fill
        // all 4 slots, top up with the next-closest entry_fee matches from any other category.
        const sameCategory = openCandidates
          .filter((candidate) => getProductCategory(candidate.name, candidate.category) === currentCategory)
          .sort(byEntryFeeProximity);
        picked = sameCategory.slice(0, RELATED_PRODUCTS_MAX);

        if (picked.length < RELATED_PRODUCTS_MAX) {
          const pickedIds = new Set(picked.map((item) => item.id));
          const otherCandidates = openCandidates
            .filter((candidate) => !pickedIds.has(candidate.id))
            .sort(byEntryFeeProximity);
          picked = picked.concat(otherCandidates.slice(0, RELATED_PRODUCTS_MAX - picked.length));
        }
      } else {
        // The current product doesn't resolve to any known category — skip category matching
        // entirely and fall back directly to closest entry_fee across all open candidates.
        picked = [...openCandidates].sort(byEntryFeeProximity).slice(0, RELATED_PRODUCTS_MAX);
      }

      setRelatedProducts(picked);
    }

    loadRelatedProducts();
    return () => { active = false; };
  }, [slug]);

  // The generated manifest (imported above, see productSeoManifest) is available synchronously
  // on the very first render, including during the Node build-time static render pass. The live
  // Supabase fetch above only resolves client-side after hydration. Preferring live data once it
  // arrives (it is fresher) but falling back to the manifest entry means the exported HTML always
  // has correct metadata, even before/without the client fetch completing.
  const staticEntry = slug ? staticProductBySlug.get(slug) : undefined;
  const metaSource = product
    ? {
        name: product.name,
        seoTitle: product.seo_title || '',
        metaDescription: product.meta_description || '',
        metaKeywords: product.meta_keywords || '',
        indexable: product.indexable !== false,
        imageUrl: product.image_url || '',
        description: product.description || '',
        entryFee: product.entry_fee || 1,
        price: product.price || 0,
        maxEntries: product.max_entries || 0,
      }
    : staticEntry
      ? {
          name: staticEntry.name,
          seoTitle: staticEntry.seoTitle,
          metaDescription: staticEntry.metaDescription,
          metaKeywords: staticEntry.metaKeywords,
          indexable: staticEntry.indexable,
          imageUrl: staticEntry.imageUrl,
          description: staticEntry.description,
          entryFee: staticEntry.entryFee,
          price: staticEntry.price || 0,
          maxEntries: staticEntry.maxEntries || 0,
        }
      : null;

  if (!metaSource && loading) {
    return (
      <>
      <Head>
        <meta name="robots" content="noindex, follow" />
      </Head>
      <View style={[styles.centerContainer, { backgroundColor: theme.background }]}>
        <ActivityIndicator color={theme.gold} size="large" accessibilityLabel="Loading" />
      </View>
      </>
    );
  }

  if (!metaSource && (fetchFailed || !slug)) {
    return (
      <>
      <Head>
        <title>Prize Not Found | JeetoBaz</title>
        <meta name="robots" content="noindex, follow" />
        <meta name="description" content="The JeetoBaz prize campaign you requested could not be found. Explore other active draws." />
      </Head>
      <View style={[styles.centerContainer, { backgroundColor: theme.background }]}>
        <Text style={[styles.notFoundCode, { color: theme.gold }]}>404</Text>
        <Text style={[styles.notFoundTitle, { color: theme.text }]}>Prize Not Found</Text>
        <Text style={[styles.notFoundMessage, { color: theme.muted }]}>
          This prize campaign does not exist, is no longer available, or the link is incorrect.
        </Text>
        <TouchableOpacity
          style={[styles.notFoundButton, { backgroundColor: theme.gold }]}
          onPress={() => router.replace('/')}
        >
          <House color="#000" size={20} />
          <Text style={styles.notFoundButtonText}>Back to Home</Text>
        </TouchableOpacity>
      </View>
      </>
    );
  }

  // metaSource is guaranteed non-null past this point (static fallback or live product).
  const meta = metaSource!;
  const pageUrl = `${BASE_URL}/product/${slug}`;
  const pageTitle = meta.seoTitle.trim() || `Win ${meta.name} in Pakistan | JeetoBaz`;
  const pageDescription = meta.metaDescription.trim()
    || meta.description.trim()
    || `Join JeetoBaz for a chance to win ${meta.name} through our transparent prize campaign.`;
  const robotsContent = meta.indexable ? 'index, follow' : 'noindex, follow';
  const ogImage = meta.imageUrl || DEFAULT_OG_IMAGE;
  const twitterImage = meta.imageUrl || DEFAULT_TWITTER_IMAGE;
  const imageAlt = slug === IPHONE_18_PRO_MAX_SLUG
    ? 'iPhone 18 Pro Max prize draw in Pakistan on JeetoBaz'
    : `${meta.name} prize campaign on JeetoBaz`;

  const currentEntries = product?.current_entries || 0;
  const maxEntries = product?.max_entries || 1;
  const spotsLeft = Math.max(maxEntries - currentEntries, 0);
  const entryFee = meta.entryFee;

  // Not typed as schema.org Product: entry_fee is the cost to enter the draw, not the price of the
  // prize being won, so a Product needs an `offers`/price to be valid -- but a schema.org
  // Offer.price here would misrepresent what's actually for sale (e.g. showing "Rs. 1" as the
  // price of a car), and there's no real review system to back `review`/`aggregateRating` either
  // (fabricating either is a Google structured-data policy risk, not just a copy nitpick). Google
  // Search Console confirmed pages using `Product` here were already invalid/ineligible for rich
  // results without one of those three, so WebPage is both the honest and the actually-working type.
  const productJsonLd = {
    ...pageSchema('WebPage', `/product/${slug}`, meta.name, pageDescription),
    ...(meta.imageUrl
      ? {
          primaryImageOfPage: {
            '@type': 'ImageObject',
            contentUrl: meta.imageUrl,
            caption: imageAlt,
          },
        }
      : {}),
  };

  const breadcrumbJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${BASE_URL}/` },
      { '@type': 'ListItem', position: 2, name: 'Explore', item: `${BASE_URL}/explore` },
      { '@type': 'ListItem', position: 3, name: meta.name, item: pageUrl },
    ],
  };

  function handleEnter() {
    if (!product) return;
    router.push({
      pathname: '/payment',
      params: {
        productId: product.id,
        productName: product.name,
        entryFee,
      },
    });
  }

  return (
    <>
    <Head>
      <title>{pageTitle}</title>
      <meta name="robots" content={robotsContent} />
      <meta name="description" content={pageDescription} />
      {meta.metaKeywords ? <meta name="keywords" content={meta.metaKeywords} /> : null}
      <link rel="canonical" href={pageUrl} />
      <meta property="og:type" content="product" />
      <meta property="og:title" content={pageTitle} />
      <meta property="og:description" content={pageDescription} />
      <meta property="og:url" content={pageUrl} />
      <meta property="og:site_name" content="JeetoBaz" />
      <meta property="og:locale" content="en_PK" />
      <meta property="og:image" content={ogImage} />
      <meta property="og:image:alt" content={pageTitle} />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@jeetobaz" />
      <meta name="twitter:title" content={pageTitle} />
      <meta name="twitter:description" content={pageDescription} />
      <meta name="twitter:image" content={twitterImage} />
      <script type="application/ld+json">{jsonLdHtml(productJsonLd)}</script>
      <script type="application/ld+json">{jsonLdHtml(breadcrumbJsonLd)}</script>
    </Head>
    <ScrollView style={[styles.container, { backgroundColor: theme.background }]}>
      <View style={[styles.header, { backgroundColor: theme.surface, borderBottomColor: theme.gold }]}>
        <TouchableOpacity onPress={goBack}>
          <Text style={[styles.backBtn, { color: theme.primary }]}>← {t('back')}</Text>
        </TouchableOpacity>
      </View>

      <View style={{ height: 260 }}>
        {meta.imageUrl ? (
          <ProductHeroImage sourceUri={meta.imageUrl} alt={imageAlt} />
        ) : (
          <View style={[styles.productImageFallback, { backgroundColor: theme.surfaceAlt }]}>
            <Ticket color={theme.gold} size={38} />
          </View>
        )}
      </View>

      <View style={[styles.body, { backgroundColor: theme.surface, borderColor: theme.border }]}>
        <Text role="heading" aria-level={1} style={[styles.productName, { color: theme.text }]}>
          {meta.name}
        </Text>

        {meta.description ? (
          <Text style={[styles.description, { color: theme.muted }]}>{meta.description}</Text>
        ) : null}

        {product ? (
          <>
            <View style={styles.priceRow}>
              <Text style={[styles.originalPrice, { color: theme.gold }]}>Rs. {product.price?.toLocaleString()}</Text>
              <View style={[styles.entryBadge, { backgroundColor: theme.goldSoft }]}>
                <Text style={[styles.entryFee, { color: theme.gold }]}>{t('entryFee')}: Rs. {entryFee}</Text>
              </View>
            </View>

            <View style={styles.iconRow}>
              <UsersRound color={theme.muted} size={16} />
              <Text style={[styles.participants, { color: theme.muted }]}>
                {currentEntries.toLocaleString()} {t('participants')} • {spotsLeft.toLocaleString()} {t('spotsLeft')}
              </Text>
            </View>

            <TouchableOpacity
              style={[styles.enterButton, { backgroundColor: theme.gold }]}
              onPress={handleEnter}
              accessibilityRole="button"
              accessibilityLabel={`${t('enterFor')} Rs.${entryFee}: ${meta.name}`}
            >
              <ButtonSheen />
              <Target color="#000" size={19} />
              <Text style={styles.enterButtonText}>{t('enterFor')} Rs.{entryFee}</Text>
            </TouchableOpacity>
          </>
        ) : (
          <ActivityIndicator color={theme.gold} style={{ marginTop: 8 }} accessibilityLabel="Loading" />
        )}
      </View>

      {slug === IPHONE_18_PRO_MAX_SLUG ? (
        <IPhone18ProMaxSeoContent
          theme={theme}
          entryFee={entryFee}
          prizeValue={meta.price}
          totalSpots={meta.maxEntries}
        />
      ) : null}

      {relatedProducts.length > 0 ? (
        <View style={styles.relatedSection}>
          <Text style={[styles.relatedTitle, { color: theme.text }]}>{t('relatedProducts')}</Text>
          <View style={styles.relatedGrid}>
            {relatedProducts.map((related) => (
              <RelatedProductCard key={related.id} product={related} theme={theme} t={t} />
            ))}
          </View>
        </View>
      ) : null}
    </ScrollView>
    </>
  );
}

function IPhone18ProMaxSeoContent({
  theme,
  entryFee,
  prizeValue,
  totalSpots,
}: {
  theme: ReturnType<typeof useAppTheme>['theme'];
  entryFee: number;
  prizeValue: number;
  totalSpots: number;
}) {
  return (
    <View style={[styles.editorialSection, { backgroundColor: theme.surface, borderColor: theme.border }]}>
      <Text role="heading" aria-level={2} style={[styles.editorialTitle, { color: theme.text }]}>
        Win iPhone 18 Pro Max in Pakistan with JeetoBaz
      </Text>
      <Text style={[styles.editorialText, { color: theme.muted }]}>
        JeetoBaz gives eligible participants in Pakistan a clear way to enter the iPhone 18 Pro Max
        prize campaign. Each entry costs Rs. {entryFee.toLocaleString()}, while the prize value shown
        for this campaign is Rs. {prizeValue.toLocaleString()}. Before entering, review the available
        spots, campaign progress, eligibility requirements and published draw information on this page.
      </Text>

      <Text role="heading" aria-level={2} style={[styles.editorialHeading, { color: theme.text }]}>
        iPhone 18 Pro Max prize draw details
      </Text>
      <View style={styles.editorialList}>
        <Text style={[styles.editorialText, { color: theme.muted }]}>• Entry fee: Rs. {entryFee.toLocaleString()} per entry</Text>
        <Text style={[styles.editorialText, { color: theme.muted }]}>• Prize value displayed: Rs. {prizeValue.toLocaleString()}</Text>
        <Text style={[styles.editorialText, { color: theme.muted }]}>• Total campaign spots: {totalSpots.toLocaleString()}</Text>
        <Text style={[styles.editorialText, { color: theme.muted }]}>• Participation: subject to JeetoBaz eligibility and campaign terms</Text>
      </View>
      <Text style={[styles.editorialText, { color: theme.muted }]}>
        The entry fee is the cost of one prize-draw entry; it is not the sale price of the iPhone.
        The live counter above shows campaign participation and remaining spots. Product variant,
        colour, storage, PTA status, warranty and fulfilment information should be read from the
        confirmed campaign details and official JeetoBaz updates before participation.
      </Text>

      <Text role="heading" aria-level={2} style={[styles.editorialHeading, { color: theme.text }]}>
        How to enter the iPhone prize campaign
      </Text>
      <View style={styles.editorialList}>
        <Text style={[styles.editorialText, { color: theme.muted }]}>1. Sign in to your verified JeetoBaz account.</Text>
        <Text style={[styles.editorialText, { color: theme.muted }]}>2. Check the entry fee, remaining spots and campaign status above.</Text>
        <Text style={[styles.editorialText, { color: theme.muted }]}>3. Tap “Enter for Rs.{entryFee.toLocaleString()}” and complete the available payment process.</Text>
        <Text style={[styles.editorialText, { color: theme.muted }]}>4. Keep your confirmed entry record and follow JeetoBaz for draw updates.</Text>
      </View>

      <Text role="heading" aria-level={2} style={[styles.editorialHeading, { color: theme.text }]}>
        Fairness, winner selection and proof
      </Text>
      <Text style={[styles.editorialText, { color: theme.muted }]}>
        The campaign proceeds according to the status, scheduling information and rules published by
        JeetoBaz. Read how the platform approaches equal entries and winner selection on the{' '}
        <Link href="/why-fair" style={[styles.editorialLink, { color: theme.primary }]}>Why JeetoBaz Is Fair</Link>{' '}
        page, and review the verification process on the{' '}
        <Link href="/transparency" style={[styles.editorialLink, { color: theme.primary }]}>Transparency</Link>{' '}
        page. Completed campaign results and available winner evidence can be checked in the{' '}
        <Link href="/winner" style={[styles.editorialLink, { color: theme.primary }]}>Past Winners</Link>{' '}
        section.
      </Text>

      <Text role="heading" aria-level={2} style={[styles.editorialHeading, { color: theme.text }]}>
        Frequently asked questions
      </Text>
      <Text role="heading" aria-level={3} style={[styles.faqQuestion, { color: theme.text }]}>
        How much does one iPhone 18 Pro Max entry cost?
      </Text>
      <Text style={[styles.editorialText, { color: theme.muted }]}>
        One entry currently costs Rs. {entryFee.toLocaleString()}. Always confirm the amount shown on
        the payment screen before completing your transaction.
      </Text>
      <Text role="heading" aria-level={3} style={[styles.faqQuestion, { color: theme.text }]}>
        When will the winner be selected?
      </Text>
      <Text style={[styles.editorialText, { color: theme.muted }]}>
        Follow the live campaign status and any draw schedule displayed by JeetoBaz. A date should not
        be assumed unless it is officially shown on the campaign page or announced through an official
        JeetoBaz channel.
      </Text>
      <Text role="heading" aria-level={3} style={[styles.faqQuestion, { color: theme.text }]}>
        Where can I read the complete rules?
      </Text>
      <Text style={[styles.editorialText, { color: theme.muted }]}>
        Review the{' '}
        <Link href="/terms" style={[styles.editorialLink, { color: theme.primary }]}>Terms and Conditions</Link>{' '}
        before entering. For common account, payment and campaign questions, visit the{' '}
        <Link href="/faq" style={[styles.editorialLink, { color: theme.primary }]}>JeetoBaz FAQ</Link>.
      </Text>

      <Link href="/explore" style={[styles.editorialCta, { color: theme.primary, borderColor: theme.primary }]}>
        Explore more active prize campaigns
      </Link>
    </View>
  );
}

function RelatedProductCard({
  product,
  theme,
  t,
}: {
  product: Product;
  theme: ReturnType<typeof useAppTheme>['theme'];
  t: (key: TranslationKey) => string;
}) {
  const spotsLeft = Math.max(product.max_entries - (product.current_entries || 0), 0);

  if (!product.slug) return null;

  return (
    <Link href={`/product/${product.slug}`} asChild>
      <TouchableOpacity
        style={StyleSheet.flatten([styles.relatedCard, { backgroundColor: theme.surface, borderColor: theme.border }])}
        accessibilityRole="link"
        accessibilityLabel={`${product.name}: ${t('entryFee')} Rs.${product.entry_fee || 1}`}
      >
        {product.image_url ? (
          <ExpoImage
            source={{ uri: product.image_url }}
            accessibilityLabel={`${product.name} prize`}
            contentFit="contain"
            cachePolicy="disk"
            style={styles.relatedImage}
          />
        ) : (
          <View style={[styles.relatedImageFallback, { backgroundColor: theme.surfaceAlt }]}>
            <Ticket color={theme.gold} size={26} />
          </View>
        )}
        <Text numberOfLines={2} style={[styles.relatedName, { color: theme.text }]}>{product.name}</Text>
        <View style={[styles.relatedEntryBadge, { backgroundColor: theme.goldSoft }]}>
          <Text style={[styles.relatedEntryFee, { color: theme.gold }]}>{t('entryFee')}: Rs. {product.entry_fee || 1}</Text>
        </View>
        <Text numberOfLines={1} style={[styles.relatedSpots, { color: theme.muted }]}>{spotsLeft.toLocaleString()} {t('spotsLeft')}</Text>
      </TouchableOpacity>
    </Link>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  centerContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },

  notFoundCode: { fontSize: 80, fontWeight: '800', marginBottom: 8 },
  notFoundTitle: { fontSize: 26, fontWeight: '700', marginBottom: 12 },
  notFoundMessage: { fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 32, maxWidth: 400 },
  notFoundButton: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 14, paddingHorizontal: 28, borderRadius: 12 },
  notFoundButtonSecondary: { backgroundColor: 'transparent', borderWidth: 1, marginTop: 12 },
  notFoundButtonText: { color: '#000', fontSize: 16, fontWeight: '700' },

  header: { padding: 20, borderBottomWidth: 2 },
  backBtn: { fontSize: 16, fontWeight: 'bold' },

  productImageFallback: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  body: { margin: 15, borderRadius: 16, borderWidth: 1, padding: 20 },

  relatedSection: { paddingHorizontal: 15, marginTop: 5, marginBottom: 30 },
  relatedTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12 },
  relatedGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  relatedCard: { width: '47%', borderRadius: 12, borderWidth: 1, padding: 10 },
  relatedImage: { width: '100%', height: 90, marginBottom: 8 },
  relatedImageFallback: { width: '100%', height: 90, marginBottom: 8, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
  relatedName: { fontSize: 13, fontWeight: '700', marginBottom: 8, minHeight: 34 },
  relatedEntryBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginBottom: 6 },
  relatedEntryFee: { fontSize: 11, fontWeight: '700' },
  relatedSpots: { fontSize: 11 },
  productName: { fontSize: 22, fontWeight: 'bold', marginBottom: 10 },
  description: { fontSize: 14, lineHeight: 20, marginBottom: 16 },

  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  originalPrice: { fontSize: 18, fontWeight: 'bold', textDecorationLine: 'line-through' },
  entryBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  entryFee: { fontSize: 13, fontWeight: '700' },

  iconRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 20 },
  participants: { fontSize: 13 },

  enterButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 16, borderRadius: 12, overflow: 'hidden' },
  enterButtonText: { fontSize: 16, fontWeight: 'bold', color: '#000' },
  editorialSection: { marginHorizontal: 15, marginBottom: 22, borderRadius: 16, borderWidth: 1, padding: 20 },
  editorialTitle: { fontSize: 22, lineHeight: 29, fontWeight: '800', marginBottom: 12 },
  editorialHeading: { fontSize: 18, lineHeight: 25, fontWeight: '800', marginTop: 18, marginBottom: 8 },
  editorialText: { fontSize: 14, lineHeight: 22, marginBottom: 9 },
  editorialList: { gap: 3, marginBottom: 8 },
  editorialLink: { fontWeight: '700', textDecorationLine: 'underline' },
  faqQuestion: { fontSize: 15, lineHeight: 22, fontWeight: '800', marginTop: 8, marginBottom: 4 },
  editorialCta: { alignSelf: 'flex-start', borderWidth: 1, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 14, fontWeight: '800', marginTop: 12 },
});
