-- SEMrush flagged 37+ product pages as keyword-cannibalizing each other because ~42 products
-- shared a near-identical meta_description template ("Enter the JeetoBaz draw for a chance to
-- win the [X]. Enjoy secure entries, transparent winner selection, verified winners, and a fair
-- prize draw experience."), making it hard for Google to differentiate pages for generic queries.
-- Rewrote each to be product-specific (price, entry fee, real features). Applied directly to
-- production via Supabase MCP; this file records the change. Pure content update — no schema
-- change, no code change, product SEO title/name/description columns untouched.

update products set meta_description = 'Win a Honda ICON e Electric Scooter (worth Rs. 419,900) for just Rs. 400 entry. Eco-friendly city commuting, smooth ride, verified JeetoBaz draw.' where slug = 'win-honda-icon-e-electric-scooter-on-jeetobaz-pakistan';
update products set meta_description = 'Win a PrisMAX 50" QLED Google TV worth Rs. 99,900 for only Rs. 100. Stunning 4K QLED visuals, Google TV smart streaming, verified JeetoBaz draw.' where slug = 'win-prismax-qled-google-tv-50-on-jeetobaz-pakistan';
update products set meta_description = 'Win a Canon EOS R10 Mirrorless Camera with 18-45mm lens (Rs. 283,900) for Rs. 100 entry. Fast autofocus, 4K video, ideal for creators. Enter now.' where slug = 'win-canon-eos-r10-camera-with-18-45mm-lens-on-jeetobaz-pakistan';
update products set meta_description = 'Win a GoPro HERO 4K Compact Action Camera (Rs. 50,000) for just Rs. 50. Waterproof, rugged, smooth 4K stabilized video for travel & sports.' where slug = 'win-gopro-hero-4k-compact-action-camera-on-jeetobaz-pakistan';
update products set meta_description = 'Win a GoPro HERO13 Black Action Camera (Rs. 96,000) for Rs. 100 entry. Ultra-smooth stabilization, waterproof build, built for adventure creators.' where slug = 'win-gopro-hero13-black-action-camera-on-jeetobaz-pakistan';
update products set meta_description = 'Win a Nikon Z5 full-frame Mirrorless Camera with 24-200mm lens (Rs. 542,000) for Rs. 200. Advanced autofocus, exceptional image quality. Enter now.' where slug = 'win-nikon-z5-camera-with-24-200mm-lens-on-jeetobaz-pakistan';
update products set meta_description = 'Win a DJI Mini 3 Pro Drone Camera (Rs. 284,999) for just Rs. 100 entry. Advanced flight tech, cinematic aerial video, lightweight portable design.' where slug = 'win-dji-mini-3-pro-drone-camera-on-jeetobaz-pakistan';
update products set meta_description = 'Win Apple AirPods Pro 3 (Rs. 67,999) for only Rs. 50 entry. Active Noise Cancellation, Transparency Mode, seamless Apple connectivity. Enter today.' where slug = 'win-apple-airpods-pro-3-on-jeetobaz-pakistan';
update products set meta_description = 'Win an Aurafit NEXA 6 UB6 PRO Smartwatch (Rs. 10,000) for just Rs. 10 entry. Health monitoring, smart notifications, stylish modern design.' where slug = 'win-aurafit-nexa-6-ub6-pro-smartwatch-on-jeetobaz-pakistan';
update products set meta_description = 'Win a Delta SE 75″ 4K UHD Smart TV (Rs. 299,999) for only Rs. 100 entry. Ultra-large screen, immersive 4K picture, perfect for movies & gaming.' where slug = 'win-delta-se-75-4k-uhd-smart-tv-on-jeetobaz-pakistan';

update products set meta_description = 'Win an Apple iMac 24″ (M3 chip, 16GB RAM, 2TB SSD, Silver) worth Rs. 810,000 for just Rs. 200 entry. Powerful all-in-one desktop, stunning display.' where slug = 'win-apple-imac-24-m3-chip-16gb-ram-2tb-ssd-silver-on-jeetobaz-pakistan';
update products set meta_description = 'Win the Apple MacBook Neo 13″ (2026) with A18 Pro chip and 256GB SSD (Rs. 242,000) for just Rs. 100 entry. Liquid Retina Display, next-gen performance.' where slug = 'apple-macbook-neo-13-2026-a18-pro';
update products set meta_description = 'Win an official FIFA 2026 World Cup Trionda replica football, size 5, premium PU leather (Rs. 6,500) for just Rs. 10 entry on JeetoBaz.' where slug = 'fifa-2026-world-cup-trionda-replica-football';
update products set meta_description = 'Win a kids'' Electric Ride-On motorcycle (Rs. 19,149) for just Rs. 20 entry. Fun, safe outdoor adventure for children, verified JeetoBaz draw.' where slug = 'electric-ride-on-for-kids-toys';
update products set meta_description = 'Win the Boxing Bundle-3 training set (Rs. 25,000) for just Rs. 20 entry. Complete home boxing/fitness gear, verified JeetoBaz draw.' where slug = 'boxing-bundle-3-fitness-equipment';
update products set meta_description = 'Win an American Fitness Treadmill TH4011 (Rs. 135,000) for just Rs. 200 entry. Home cardio workouts made easy, verified JeetoBaz draw.' where slug = 'american-fitness-equipment-treadmill-th4011';
update products set meta_description = 'Win the Trading and Investing bundle of 5 books (Rs. 5,600) for just Rs. 10 entry. Learn to trade and invest smarter, verified JeetoBaz draw.' where slug = 'trading-and-investing-bundle-of-5-books';
update products set meta_description = 'Win the Financial Mastery bundle of 5 books (Rs. 3,100) for just Rs. 30 entry. Practical money and finance lessons, verified JeetoBaz draw.' where slug = 'financial-mastery-bundle-of-5-books';
update products set meta_description = 'Win a Smart e-Quran Gift Edition (AK-788) worth Rs. 10,490 for just Rs. 10 entry. Digital recitation and translation features, JeetoBaz draw.' where slug = 'smart-e-quran-gift-edition-ak-788-books';
update products set meta_description = 'Win a Dawlance DHM 390 SN built-in hob (Rs. 52,000) for just Rs. 50 entry. Upgrade your kitchen with reliable built-in cooking, JeetoBaz draw.' where slug = 'dhm-390-sn-built-in-hob-dawlance-kitchen-appliance';
update products set meta_description = 'Win a 6-Layer Steel Shoe Rack Storage Organizer (Rs. 3,490) for just Rs. 10 entry. Keep your home tidy and organized, verified JeetoBaz draw.' where slug = '6-layer-steel-shoe-rack-storage-organizer-home-living';
update products set meta_description = 'Win a PlayStation 5 Console – Ghost of Yotei Gold Limited Edition Slim (Rs. 275,000) for just Rs. 100 entry. Rare collector''s console, JeetoBaz draw.' where slug = 'playstation-5-console-ghost-of-yotei-gold-limited-edition-slim';
update products set meta_description = 'Win a brand-new Honda City 1.2LS 2026 (Rs. 4,737,000) for just Rs. 1,000 entry. Pakistan''s most trusted sedan, verified JeetoBaz car draw.' where slug = 'honda-city-1-2ls-car-2026';
update products set meta_description = 'Win an Itel A100 mobile (128GB, 4GB RAM) worth Rs. 27,499 for just Rs. 10 entry. Affordable smartphone upgrade, verified JeetoBaz draw.' where slug = 'itel-a100-mobile-128gb-4gb-ram';
update products set meta_description = 'Win P9 Wireless On-Ear Stereo Earphones (Rs. 1,149) for just Rs. 20 entry. Enjoy wireless music on the go, verified JeetoBaz draw.' where slug = 'p9-wireless-on-ear-stereo-earphones';

update products set meta_description = 'Win a Radiant Series 55″ Google TV G22 with 4K UHD picture (Rs. 121,701) for just Rs. 100 entry. Smart streaming apps, verified JeetoBaz draw.' where slug = 'win-radiant-series-google-tv-55-g22-4k-uhd-on-jeetobaz-pakistan-tvs';
update products set meta_description = 'Win a Blaze Series 40″ Google TV E22 with 2K Full HD (Rs. 74,300) for just Rs. 50 entry. Smart streaming, immersive picture, JeetoBaz draw.' where slug = 'win-blaze-series-google-tv-40-e22-2k-fhd-on-jeetobaz-pakistan-tvs';
update products set meta_description = 'Win a Kore FHD Google TV 40″ with crisp 2K Full HD (Rs. 65,300) for just Rs. 50 entry. Smart streaming apps built in, verified JeetoBaz draw.' where slug = 'win-kore-fhd-google-tv-40-2k-fhd-on-jeetobaz-pakistan';
update products set meta_description = 'Win a Canvas Series 50″ Android TV G3A with 4K UHD (Rs. 109,999) for just Rs. 100 entry. Smart Android TV functionality, JeetoBaz draw.' where slug = 'win-canvas-series-android-tv-50-g3a-4k-uhd-on-jeetobaz-pakistan-tvs';
update products set meta_description = 'Win a Xiaomi Pad 8 tablet worth Rs. 144,999 for just Rs. 100 entry. Smooth performance for entertainment and productivity, verified JeetoBaz draw.' where slug = 'win-xiaomi-pad-8-on-jeetobaz-pakistan';
update products set meta_description = 'Win a Samsung Galaxy Tab S10 Lite WiFi (6GB RAM, 128GB) worth Rs. 98,999 for just Rs. 100 entry. Powerful tablet for work and play, JeetoBaz draw.' where slug = 'win-samsung-galaxy-tab-s10-lite-wifi-6gb-ram-128gb-on-jeetobaz-pakistan';
update products set meta_description = 'Win an Apple Magic Keyboard (USB-C) MXCL3 for just Rs. 80 entry. Rechargeable Bluetooth keyboard in Silver, works with Mac & iPad. JeetoBaz draw.' where slug = 'win-apple-magic-keyboard-usb-c-mxcl3-on-jeetobaz-pakistan';
update products set meta_description = 'Win an Apple iPad Pro 11″ (2025) with M5 chip and 256GB Wi-Fi (Rs. 350,000) for just Rs. 100 entry. Stunning Ultra Retina display, JeetoBaz draw.' where slug = 'win-apple-ipad-pro-11-m5-2025-256gb-wi-fi-on-jeetobaz-pakistan';
update products set meta_description = 'Win an Apple Mac Studio (M2 Max, 32GB RAM, 512GB SSD) worth Rs. 660,000 for just Rs. 300 entry. Desktop-class power for creators, JeetoBaz draw.' where slug = 'win-apple-mac-studio-m2-max-32gb-ram-512gb-ssd-on-jeetobaz-pakistan';
update products set meta_description = 'Win an Apple Mac mini (M1 chip, 8GB RAM, 512GB SSD) worth Rs. 205,000 for just Rs. 100 entry. Compact powerful desktop, verified JeetoBaz draw.' where slug = 'win-apple-mac-mini-m1-512gb-ssd-8gb-ram-on-jeetobaz-pakistan';
update products set meta_description = 'Win a Q11 Smart Watch with built-in LED flashlight (Rs. 1,999) for just Rs. 1 entry. Handy everyday wearable, verified JeetoBaz draw.' where slug = 'q11-rough-led-flashlight-smart-watch';
update products set meta_description = 'Win a Watch 10 Max Smart Watch with double straps (Rs. 1,799) for just Rs. 1 entry. Stylish and versatile wearable, verified JeetoBaz draw.' where slug = 'watch-10-max-double-straps-smart-watch';
update products set meta_description = 'Win an Apple MagSafe Battery Pack worth Rs. 36,999 for just Rs. 50 entry. Snap-on wireless charging for iPhone, verified JeetoBaz draw.' where slug = 'apple-magsafe-battery-pack';
update products set meta_description = 'Win a Mega T+ 1 Ton Inverter Split AC (Rs. 78,999) for just Rs. 100 entry. Energy-efficient cooling for your home, verified JeetoBaz draw.' where slug = 'mega-t-inverter-10-co-inverter-split-ac';
update products set meta_description = 'Win a Lenovo Tab 7 WiFi tablet worth Rs. 33,999 for just Rs. 30 entry. Great for entertainment and everyday use, verified JeetoBaz draw.' where slug = 'lenovo-tab-7-wifi';
update products set meta_description = 'Win an Anker MagGo 10000mAh 35W power bank with built-in USB-C cable (Rs. 21,499) for just Rs. 20 entry. Fast charging on the go, JeetoBaz draw.' where slug = 'anker-maggo-10000mah-35w-powerbank-with-built-in-usb-c-cable';
update products set meta_description = 'Win a Dell Latitude 15 3540 laptop (13th Gen Core i7, 8GB RAM, 512GB SSD) worth Rs. 251,999 for just Rs. 100 entry. Verified JeetoBaz draw.' where slug = 'dell-latitude-15-3540-15-6-inches-13th-gen-core-i7-dos-8gb-512gb-laptop';
